config/routes.rb
Rails.application.routes.draw do

  resources :users

  resources :projects do
    resources :tasks
    resources :memberships
  end

  root 'welcome#index'

  get 'about' => 'pages#about'

  get 'terms' => 'pages#terms'

  get 'faq' => 'pages#faq'

  get '/sign-up' => 'registrations#new', as: :signup

  post '/sign-up' => 'registrations#create'

  get '/sign-in' => 'authentication#new', as: :signin

  post '/sign-in' => 'authentication#create'

  get '/sign-out' => 'authentication#destroy', as: :signout

end

app/models/task.rb
class Task < ActiveRecord::Base

  validates :description, presence: true
  validate :date_cannot_be_in_the_past

  belongs_to :project

  def date_cannot_be_in_the_past
    if due_date.present? && due_date < Date.today
      errors.add(:date, "can't be in the past")
    end
  end

  def due_within_week?
    if due_date != nil
      due_date - Date.today <= 7
    end
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action do
    @project = Project.find(params[:project_id])
  end

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = @project.tasks
    if params[:complete]== 'false'
      @tasks = @tasks.where(:complete=>false)
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = @project.tasks.find(params[:id])
  end

  # GET /tasks/new
  def new
    @task = @project.tasks.new
  end

  # GET /tasks/1/edit
  def edit
    @task = @project.tasks.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = @project.tasks.new(task_params)
    if @task.save
      redirect_to project_task_path(@project, @task), notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    @task = @project.tasks.find(params[:id])
      if @task.update(task_params)
        redirect_to project_task_path(@project, @task), notice: 'Task was successfully updated.'
      else
        render :edit
      end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = @project.tasks.find(params[:id])
    @task.destroy
    redirect_to project_tasks_path(@project), notice: 'Task was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = @project.tasks.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:description, :complete, :due_date, :project_id)
    end
end

app/views/tasks/_form.html.erb
<%= render partial: 'shared/errors', locals: {feature: @task} %>
<%= form_for([@project, @task], html: {class: "form-horizantal"}) do |f| %>
  <div class="row">
    <div class="form-group">
      <%= f.label :description, class: "col-sm-offset-1 col-sm-1 control-label" %>
      <div class="col-sm-7">
      <%= f.text_field :description, class: "form-control" %>
      </div>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="form-group">
      <%= f.label :due_date, class: "col-sm-offset-1 col-sm-1 control-label" %>
      <div class="col-sm-7">
      <%= f.date_field :due_date, class: "form-control" %>
      </div>
    </div>
  </div>
  <% if @task.persisted? %>
    <div class="row">
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-12">
          <div class="checkbox">
            <label>
              <%= f.check_box :complete %>Complete
            </label>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <br>
  <div class="row">
  <div class="form-group col-sm-12 col-sm-offset-2">
    <%= f.submit class: "btn btn-primary"%>
    <%= link_to 'Cancel', project_tasks_path(@project), class: "btn btn-default" %>
  </div>
  </div>


<% end %>

app/views/tasks/edit.html.erb
<div class="container">
  <div class="page-header">
    <h1>Edit Task</h1>
  </div>

    <%= render 'form' %>


  </div>

app/views/tasks/index.csv.erb
<%- headers = ['Tasks'] -%>
<%= CSV.generate_line headers %>
<%- @tasks.each do |task| -%>
  <%= CSV.generate_line([task.description]) %>
<%- end -%>

app/views/tasks/index.html.erb
<div class="container">
  <div class="page header">
    <div class="pull-right">
      <% if params[:complete] == 'false' %>
        <%= link_to 'All Tasks', project_tasks_path(@project), class: "btn btn-link" %>|
        <%= link_to 'Incomplete Tasks', project_tasks_path(@project, :complete => false), class: "btn btn-link", disabled: "disabled" %>
      <% else %>
        <%= link_to 'All Tasks', project_tasks_path, class: "btn btn-link", disabled: "disabled" %>|
        <%= link_to 'Incomplete Tasks', project_tasks_path(@project, :complete => false), class: "btn btn-link" %>
      <% end %>
      <%= link_to 'New Task', new_project_task_path(@project), class: "btn btn-info" %>
    </div>
    <h2>Tasks for <%= @project.name %></h2>
  </div>
  <div>
    <ol class="breadcrumb">
      <li><%= link_to "Projects", projects_path %></li>
      <li><a href="#"><%= link_to @project.name, @project %></a></li>
      <li class="active">Tasks</li>
    </ol>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th style="font-size:18px">Description</th>
        <th style="font-size:18px">Complete</th>
        <th style="font-size:18px">Due</th>
        <th colspan="10"></th>
      </tr>
    </thead>

    <tbody>
      <% @tasks.each do |task| %>
          <% if task.due_within_week? %>
            <tr bgcolor="#f2dede">
          <% else %>
            <tr>
          <% end %>
              <td><%= task.description %></td>
              <td><%= task.complete %></td>
              <td><%= task.due_date %></td>
              <td class="pull-right"><%= link_to 'Show', project_task_path(@project, task), class: "btn btn-success" %>
                  <%= link_to 'Edit', edit_project_task_path(@project, task), class: "btn btn-info", id: "edit-task-#{task.id}-action" %>
                  <%= link_to 'Destroy', project_task_path(@project, task), class:"btn btn-danger", id: "delete-task-#{task.id}-action", method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/tasks/new.html.erb
<div class="container">
  <div class="page-header">
    <h1>New Task</h1>
  </div>

    <%= render 'form' %>


  </div>

app/views/tasks/show.html.erb
<div class="container" id="task-alert">

  <% if notice %>
    <div class="alert alert-success" role="alert">
      <p id="notice"><%= notice %></p>
    </div>
  <% end %>

  <p>
    <strong>Description:</strong>
    <%= @task.description %>
  </p>

  <p>
    <strong>Completed:</strong>
    <%= @task.complete %>
  </p>

  <p>
    <strong>Due Date:</strong>
    <%= @task.due_date %>
  </p>

  <%= link_to 'Edit', edit_project_task_path(@project, @task) %> |
  <%= link_to 'Back', project_tasks_path(@project) %>

</div>