config/routes.rb
Rails.application.routes.draw do

  resources :users

  resources :projects do
    resources :tasks
    resources :memberships
  end

  root 'welcome#index'

  get 'about' => 'pages#about'

  get 'terms' => 'pages#terms'

  get 'faq' => 'pages#faq'

  get '/sign-up' => 'registrations#new', as: :signup

  post '/sign-up' => 'registrations#create'

  get '/sign-in' => 'authentication#new', as: :signin

  post '/sign-in' => 'authentication#create'

  get '/sign-out' => 'authentication#destroy', as: :signout

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :first_name, :last_name, :email, presence: true
  validates :email, uniqueness: true
  has_secure_password

  has_many :memberships
  has_many :projects, through: :memberships

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/users_controller.rb
class UsersController <ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      redirect_to users_path, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path, notice: 'User was successfully deleted.'
  end

  private
  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :email,
      :password,
      :password_confirmation,
      :role
    )
  end

end

app/views/users/_form.html.erb
<%= render partial: 'shared/errors', locals: {feature: @user} %>
<%= form_for(@user, html: {class: "form-horizantal"}) do |f| %>
  <div class="row">
    <div class="form-group">
      <%= f.label :first_name, class: "col-sm-2 control-label" %>
      <div class="col-sm-7">
      <%= f.text_field :first_name, class: "form-control" %>
      </div>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="form-group">
      <%= f.label :last_name, class: "col-sm-2 control-label" %>
      <div class="col-sm-7">
      <%= f.text_field :last_name, class: "form-control" %>
      </div>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="form-group">
      <%= f.label :email, class: "col-sm-2 control-label" %>
      <div class="col-sm-7">
      <%= f.email_field :email, class: "form-control" %>
      </div>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="form-group">
      <%= f.label :password, class: "col-sm-2 control-label" %>
      <div class="col-sm-7">
      <%= f.password_field :password, class: "form-control" %>
      </div>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="form-group">
      <%= f.label :password_confirmation, class: "col-sm-2 control-label" %>
      <div class="col-sm-7">
      <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>
    </div>
  </div>
  <br>
  <div class="row">
  <div class="form-group col-sm-12 col-sm-offset-2">
    <%= f.submit class: "btn btn-primary"%>
    <%= link_to 'Cancel', users_path, class: "btn btn-default" %>
  </div>
</div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="page-header">
    <h1>Edit User</h1>
</div>

  <%= render "form" %>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="page header">
    <div class="pull-right">
      <%= link_to 'New User', new_user_path, class: "btn btn-info" %>
    </div>
    <h2>Users</h2>
    <% if notice %>
      <div class="alert alert-success text-center" role="alert">
        <p id="notice"><%= notice %></p>
      </div>
    <% end %>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th style="font-size:18px">Name</th>
        <th style="font-size:18px">Email</th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= link_to "#{user.first_name} #{user.last_name}", user_path(user) %></td>
          <td><a href="mailto:<%= user.email %>"><%= user.email %></a></td>
          <td class="pull-right"><%= link_to 'edit', edit_user_path(user), id: "edit-user-#{user.id}-action" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/users/new.html.erb
<div class="container">
  <div class="page-header">
    <h1>New User</h1>
  </div>
    <%= render "form" %> 
  </div>

app/views/users/show.html.erb
<div class="container">
  <div class="page header">
    <div class="pull-right">
      <%= link_to 'Edit', edit_user_path(@user), class: "btn btn-info" %>
    </div>
    <h2><%= @user.first_name %> <%= @user.last_name %></h2>

    <br>
    <dl class="dl-horizontal">
      <dt><p>First name</dt> <dd><%= @user.first_name %></p></dd>
      <dt><p>Last name</dt> <dd><%= @user.last_name %></p></dd>
      <dt><p>Email</dt> <dd><a href="mailto:<%= @user.email %>"><%= @user.email %></a></p></dd>
    </dl>

</div>