config/routes.rb
Rails.application.routes.draw do

  resources :users

  resources :projects do
    resources :tasks
    resources :memberships
  end

  root 'welcome#index'

  get 'about' => 'pages#about'

  get 'terms' => 'pages#terms'

  get 'faq' => 'pages#faq'

  get '/sign-up' => 'registrations#new', as: :signup

  post '/sign-up' => 'registrations#create'

  get '/sign-in' => 'authentication#new', as: :signin

  post '/sign-in' => 'authentication#create'

  get '/sign-out' => 'authentication#destroy', as: :signout

end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, presence: true

  has_many :tasks

  has_many :memberships
  has_many :users, through: :memberships
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to project_path(@project), notice: "Project was successfully created."
    else
      render :new
    end
  end

  def show
    @project = Project.find(params[:id])
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    @project.update(project_params)
    if @project.save
      redirect_to project_path(@project), notice: "Project was successfully updated."
    else
      render :new
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path, notice: "Project was successfully deleted."
  end

  private
  def project_params
    params.require(:project).permit(
      :name
    )
  end
end

app/views/projects/_form.html.erb
<%= render partial: 'shared/errors', locals: {feature: @project} %>
<%= form_for(@project, html: {class: "form-horizantal"}) do |f| %>
  <div class="row">
    <div class="form-group">
      <%= f.label :name, class: "col-sm-offset-1 col-sm-1 control-label" %>
      <div class="col-sm-7">
      <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>
  </div>
  <br>

  <br>
  <div class="row">
  <div class="form-group col-sm-12 col-sm-offset-2">
    <%= f.submit class: "btn btn-primary"%>
    <%= link_to 'Cancel', projects_path, class: "btn btn-default" %>
  </div>
</div>
<% end %>

app/views/projects/edit.html.erb
<div class="container">
  <div class="page-header">
    <h1>Edit Project</h1>
  </div>
    <%= render "form" %>

  </div>

app/views/projects/index.html.erb
<div class="container">
  <div class="page header">
    <div class="pull-right">
      <%= link_to 'New Project', new_project_path, class: "btn btn-info" %>
    </div>
    <h2>Projects</h2>
  </div>

  <% if notice %>
    <div class="alert alert-success text-center" role="alert">
      <p id="notice"><%= notice %></p>
    </div>
  <% end %>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Tasks</th>
        <th>Members</th>
      </tr>
    </thead>

    <tbody>
      <% @projects.each do |project| %>
        <tr>
          <td class="col-md-3"><%= link_to "#{project.name}", project_path(project) %></td>
          <td><%= link_to "#{project.tasks.length}", project_tasks_path(project) %></td>
          <td><%= link_to "#{project.memberships.length}", project_memberships_path(project) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/projects/new.html.erb
<div class="container">
  <div class="page-header">
    <h1>Create Project</h1>
  </div>
    <%= render "form" %>

  </div>

app/views/projects/show.html.erb
<div class="container">
  <div class="page header">
    <p>
    <% if notice %>
      <div class="alert alert-success text-center" role="alert">
        <p id="notice"><%= notice %></p>
      </div>
    <% end %>
  </p>
    <div class="pull-right">
      <%= link_to 'Edit', edit_project_path(@project), class: "btn btn-info" %>
      <%= link_to 'Delete', @project, class: "btn btn-danger", method: :delete, data: {confirm: "Are you sure?"} %>
    </div>
    <h2><%= @project.name %></h2>
    <p>
      <br>
      <ol class="breadcrumb">
        <li><%= link_to "Projects", projects_path %></li>
        <li class="active"><%= @project.name %></li>
      </ol>
    </p>
    <div class="projectshow">
      <%= link_to "#{@project.tasks.length} Tasks", project_tasks_path(@project) %>
    </div>
    <p></p>
    <div class="projectshow">
      <%= link_to "#{@project.memberships.length} Members", project_memberships_path(@project) %>
    </div>
</div>