config/routes.rb
Rails.application.routes.draw do

  resources :users

  resources :projects do
    resources :tasks
    resources :memberships
  end

  root 'welcome#index'

  get 'about' => 'pages#about'

  get 'terms' => 'pages#terms'

  get 'faq' => 'pages#faq'

  get '/sign-up' => 'registrations#new', as: :signup

  post '/sign-up' => 'registrations#create'

  get '/sign-in' => 'authentication#new', as: :signin

  post '/sign-in' => 'authentication#create'

  get '/sign-out' => 'authentication#destroy', as: :signout

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GCamp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container container-fluid">
      <div class="container">
        <div class="row">
          <ul class="nav navbar-nav">
            <li><%= link_to 'gCamp', root_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li><%= link_to "#{current_user.first_name} #{current_user.last_name}", current_user %></li>
              <li><%= link_to "Sign Out", signout_path %></li>
            <% else %>
              <li><a href="/sign-up">Sign Up</a></li>
              <li><a href="/sign-in"> Sign In</a></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </nav>



<%= yield %>
<footer>
<nav class="navbar navbar-default navbar-fixed-bottom" role="navigation" id="footer">
  <div class="container container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
      <ul class="nav navbar-nav">
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'Terms', terms_path %></li>
        <li><%= link_to 'FAQ', faq_path %></li>
        <li><%= link_to 'Users', users_path %></li>
        <li><%= link_to 'Projects', projects_path %></li>
      </ul>
  </div><!-- /.container-fluid -->
</nav>
</footer>


</body>
</html>